from django.db import models

class geic50(models.Model):
    probe_set_id = models.CharField(max_length=50)
    dutch_t_p = models.CharField(max_length=100)
    dutch_t_stat = models.CharField(max_length=100)
    dutch_w_p = models.CharField(max_length=100)
    dutch_w_stat = models.CharField(max_length=100)
    totxv_t_p = models.CharField(max_length=100)
    totxv_t_stat = models.CharField(max_length=100)
    totxv_w_p = models.CharField(max_length=100)
    totxv_w_stat = models.CharField(max_length=100)
    totxvi_t_p = models.CharField(max_length=100)
    totxvi_t_stat = models.CharField(max_length=100)
    totxvi_w_p = models.CharField(max_length=100)
    totxvi_w_stat = models.CharField(max_length=100)
    meta_p = models.CharField(max_length=100)
    meta_stat = models.CharField(max_length=100)
    drug = models.CharField(max_length=100)

class gemeth(models.Model):
    probe_set_id = models.CharField(max_length=50)
    ilmn_id = models.CharField(max_length=50)
    totxv_t_p = models.CharField(max_length=100)
    totxv_t_stat = models.CharField(max_length=100)
    totxv_w_p = models.CharField(max_length=100)
    totxv_w_stat = models.CharField(max_length=100)
    totxvi_t_p = models.CharField(max_length=100)
    totxvi_t_stat = models.CharField(max_length=100)
    totxvi_w_p = models.CharField(max_length=100)
    totxvi_w_stat = models.CharField(max_length=100)
    meta_p = models.CharField(max_length=100)
    meta_stat = models.CharField(max_length=100)
    gene_symbol = models.CharField(max_length=100)
    chr = models.CharField(max_length=100)
    distance = models.CharField(max_length=100)
    samechr = models.CharField(max_length=50)

class gemir(models.Model):
    probe_set_id = models.CharField(max_length=50)
    exiqon_id = models.CharField(max_length=50)
    microrna = models.CharField(max_length=50)
    totxv_t_p = models.CharField(max_length=100)
    totxv_t_stat = models.CharField(max_length=100)
    totxv_w_p = models.CharField(max_length=100)
    totxv_w_stat = models.CharField(max_length=100)
    totxvi_t_p = models.CharField(max_length=100)
    totxvi_t_stat = models.CharField(max_length=100)
    totxvi_w_p = models.CharField(max_length=100)
    totxvi_w_stat = models.CharField(max_length=100)
    meta_p = models.CharField(max_length=100)
    meta_stat = models.CharField(max_length=100)
    gene_symbol = models.CharField(max_length=100)
    chr = models.CharField(max_length=100)
    energy = models.CharField(max_length=100)
    score = models.CharField(max_length=50)
    mirna_align = models.CharField(max_length=50)
    align = models.CharField(max_length=50)
    gene_align = models.CharField(max_length=50)
